[package]
name = "enseirb-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [ "Romain PIERRE <https://romainpierre7.github.io/Portfolio/>", Mathias APARICIO <https://github.com/mathias-aparicio>" ]
license = "MIT"
description = "Unofficial template for ENSEIRB-MATMECA reports"
repository = "https://github.com/RomainPierre7/ENSEIRB-report-template"
keywords = [ "enseirb", "matmeca", "internship", "stage", report, rapport ]
categories = [ "report" ]
disciplines = [ "engineering", "computer-science" ]
compiler = "0.11.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"